### ISSUE TITLE
There is no '+' key in American keyboard layout

### ISSUE THREAD

**Issue by buckle2000** [rm-code/lofivi#10]
There is only '=' key.

**Comment by rm-code** [comment]
Pushed an update which changes the default keys in the config file.

You'll have to delete the current config file for the changes to take place (not you can further change the key layout in that file).

This is the default location for LÖVE's savegame folders:
- Windows Vista and 7: C:\Users\user\AppData\Roaming\LOVE or %appdata%\LOVE\
- Linux: $XDG_DATA_HOME/love/ or ~/.local/share/love/
- Mac: /Users/user/Library/Application Support/LOVE/

**Comment by davisdude** [comment]
There actually is a plus key,  just not on most laptop keyboards. It's
right next to the numpad

On Aug 24, 2016 6:46 PM, "Robert Machmer" notifications@github.com wrote:

Pushed an update which changes the default keys in the config file.

You'll have to delete the current config file for the changes to take place
(not you can further change the key layout in that file).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/rm-code/lofivi/issues/10#issuecomment-242232095, or mute
the thread

**Comment by rm-code** [comment]
I know :) I had the same complaint in the https://github.com/rm-code/logivi repo and it got fixed by allowing multiple key bindings in the config: https://github.com/rm-code/logivi/pull/21.

I just don't have the time at the moment to properly change it so if one of you is up for an PR I'll gladly merge it ;)
